### ISSUE TITLE
Memory hogging

### ISSUE THREAD

**Issue by owais-redhunt** [redhuntlabs/BucketLoot#3]
There appears to be an issue where if an S3 bucket has too many large files, it clogs up RAM and causes the system to freeze.

Upon reviewing, I've determined that this is due to you storing data in a byte slice every time the tool makes a request. A workaround here would be to write to secondary or disk storage, and read it from there. This may be a bit slower than storing it in RAM (especially with a HDD), but is better than a crashing and freezing toolm in my opinion.

**Comment by 0x4f53** [comment]
@umair9747 Created ~~#5~~ #7
